[tool.flake8]
max-doc-length = 72
statistics = true
max-complexity = 10
max-expression-complexity = 5
cohesion-below = 66
max-function-length = 50
max-parameters-amount = 3

[tool.pytest.ini_options]
addopts = """
--cov=tests 
--cov-config=/home/victor-files/projects/musicinpython/pyproject.toml 
--cov-branch 
--cov-report=term 
--cov-report=lcov:./coverage.lcov
"""

[tool.coverage]
[tool.coverage.report]
exclude_lines = [
              "pragma: no cover",
              "if __name__ == .__main__.:",
              "def ([a-z_])+input",
              "def ([a-z_])+interface",
              "def display"]
ignore_errors = true
skip_empty = true
sort = "-cover"
